### PR TITLE
Revert "Update certificate bundle."

### PR DESCRIPTION
**Pull request by sigmavirus24**
Reverts kennethreitz/requests#2442

### CODE REVIEW

**Comment by Lukasa** [comment]
We may need to merge this to temporarily resolve the CA problems added in 2.5.2.

**Comment by sigmavirus24** [comment]
And then we'll cut 2.5.3

**Comment by Lukasa** [comment]
:sob:

**Comment by sigmavirus24** [comment]
Yeah. This is the worst

**Pull request merged**
