### PR TITLE
__version__.py

### PR DESCRIPTION
**Pull request by kennethreitz**

### CODE REVIEW

**Comment by kennethreitz** [comment]
waiting for ci to pass before merging

**Comment by kennethreitz** [comment]
P.S. I'll be happy to pay Travis money if it means our tests will run faster. /cc @Lukasa

**Comment by nateprewitt** [comment]
I think appveyor is our bottleneck right now because it won't parallelize tests with the free version.

Also just wanted to make sure you'd seen #4058.

**Comment by kennethreitz** [comment]
They'll only give you two concurrent builds at a time with paid though... sucks.

**Comment by kennethreitz** [comment]
And it's vastly overpriced for that.

**Comment by nateprewitt** [comment]
Yeah, not worth it for only one additional build slot.

**Comment by kennethreitz** [comment]
this is the longest ci run in history. almost makes me want to setup a jenkins again.

wonder if there's a better paid-for ci service we could use.

**Comment by kennethreitz** [comment]
i really don't like this waiting around stuff.

**Comment by kennethreitz** [comment]
wtf this is ridiculous

**Comment by kennethreitz** [comment]
omg

**Comment by nateprewitt** [comment]
I think you've got builds queued up on appveyor. If you cancel the old ones, it'll speed things up.

**Comment by sethmlarson** [comment]
Has the option to cancel old builds when superceded by a new commit for a PR been activated on Travis CI? Greatly speeds up build queue flushing for PRs. It's a newer feature. I'm not aware of a similar feature for AppVeyor.

**Comment by sethmlarson** [comment]
Also doesn't Python 2.7 not have `exec()`? I only see `eval()` on the built-ins list.

**Pull request merged**
