### PR TITLE
Bug fix: field uri in digest authentication should not be empty when enc...

### PR DESCRIPTION
**Pull request by luozhaoyu**
...ounter http redirections.

https://github.com/kennethreitz/requests/issues/2426

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I haven't read this yet, and I'm certain it really is this simple, but I want to re read the RFC about this regardless to make sure this applies to all cases. I suppose we've never had trouble with this because people were using URIs that had paths when authenticating. It doesn't hurt to be safe though. =)

Thanks for your patience @luozhaoyu

**Comment by luozhaoyu** [comment]
@sigmavirus24 Sure! It is rare because I could only reproduce it when use a proxy and encounter a redirect...

**Comment by sigmavirus24** [comment]
I'm comfortable with this. Sorry for the delay @luozhaoyu. I lost track of this.

Thoughts @Lukasa?

**Comment by Lukasa** [comment]
Fine by me. =)

**Comment by sigmavirus24** [comment]
Thanks @luozhaoyu

**Comment by luozhaoyu** [comment]
@sigmavirus24 You're welcome!

**Pull request merged**
