### PR TITLE
Update Quickstart documentation of Response.json()

### LINKED ISSUE #2799: Quickstart note about json rendering is misleading
In the Quickstart document, the [JSON Response Content](http://docs.python-requests.org/en/v2.0-0/user/quickstart/#json-response-content) section says:

> In case the JSON decoding fails, `r.json` raises an exception. For example, if the response gets a 401 (Unauthorized), attempting `r.json` raises `ValueError: No JSON object could be decoded`

This is a bit misleading, especially that the [`json()`](https://github.com/kennethreitz/requests/blob/v2.7.0/requests/models.py#L798) method makes no attempt to validate that. It is accurate to say that failure to decode JSON will result in an error being raised. However, receiving 401 does not necessarily mean that JSON decoding will fail. Some APIs might return a JSON object in the response body (e.g. `{ 'error': 'Unauthorized' }`), in which case `r.json()` will work fine.

### PR DESCRIPTION
**Pull request by hosamaly**
Fixes #2799

### CODE REVIEW

**Comment by Lukasa** [comment]
This is really good! One note: can we remove the reference to `response.ok`? It's at risk of deprecation, so I'd rather not add new references to it.

**Comment by hosamaly** [comment]
Thanks. I beg to differ on `response.ok`. I find it useful and advise people to use it, although I'd prefer to change its implementation to avoid raising and catching exceptions. It could be as simple as `return self.status_code < 400`. I could update the pull request if you wish.

**Comment by Lukasa** [comment]
The problem with `ok` is that it's not entirely clear what exactly it means: it's ambiguous and weird. Changing it would be better, yeah. =)

**Comment by hosamaly** [comment]
I've updated the implementation of `ok` and added a docstring to it.

**Comment by Lukasa** [comment]
Sorry, that was me being really unclear. I didn't want you to change `ok` itself, I wanted you to change the reference to it. =( Sorry.

**Comment by hosamaly** [comment]
Feel free to edit the description to fit your needs. I still think using `ok` is clearer for new users (to whom the Quickstart guide is targeted), IMHO.

**Comment by Lukasa** [comment]
To be clear, I'm not going to accept a change to the implementation of `ok`, especially one that changes the contract. If you'd rather not make further changes to this, that's fine, I can merge it and make the changes myself.

**Comment by hosamaly** [comment]
My change to the implementation of `ok` certainly did not change the contract; it still behaves exactly the same. And certainly feel free to accept it or not; it isn't really important.

I'm just not comfortable changing the reference to `ok` in the Quickstart guide, so I'd rather you do it yourself if you really think it's better without it.

**Comment by sigmavirus24** [comment]
@Lukasa would you like to revert these changes, or should I?

**Comment by Lukasa** [comment]
Thanks so much @hosamaly!

**Comment by hosamaly** [comment]
You're welcome @Lukasa . Thanks for accepting it.

**Pull request merged**
