### PR TITLE
Proposed 2.8.0

### PR DESCRIPTION
**Pull request by sigmavirus24**
Includes

- #2674 
- #2567 
- #2523 
- #2706
- Bump for urllib3

Reminder to look at http://ci.kennethreitz.org/job/requests-pr/ for build status

### CODE REVIEW

**Comment by sigmavirus24** [comment]
So http://ci.kennethreitz.org/job/requests-pr/714/PYTHON=3.3/console is an interesting error. I'll work on tracking it down

**Comment by sigmavirus24** [comment]
Here's hoping http://ci.sigmavir.us/job/requests-real/ picks up on this. @kennethreitz's CI is not picking up on the new commits.

**Comment by sigmavirus24** [comment]
Ah, here we go: http://ci.kennethreitz.org/job/requests-pr/715/

**Comment by kennethreitz** [comment]
Let's be extra cautious of #2567

**Comment by Lukasa** [comment]
We are. That's why we're shipping it in 2.8.0: it should avoid us immediately breaking a ton of production software. =)

**Comment by sigmavirus24** [comment]
@kennethreitz #2567 is already running on Debian (and maybe ubuntu?) against Requests 2.7.0 and has yet to produce any bug reports there. It's been running there for _at least_ a month. Also iirc, Cramer signed off on it and pip has been using something similar to #2567 for a while now.

**Comment by kennethreitz** [comment]
what does @mitsuhiko think?

**Comment by mitsuhiko** [comment]
Replied to #2567.

**Comment by mmedal** [comment]
Any traction on this release? Would love to see https://github.com/shazow/urllib3/issues/556 fixed :)

**Comment by lra** [comment]
> Any traction on this release? Would love to see shazow/urllib3#556 fixed :)

+1

**Comment by sigmavirus24** [comment]
## Sorry Laurent. What are you trying to add 1 to? This isn't JavaScript so we don't do auto type coercion and that comment doesn't parse.

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lra** [comment]
Heh, sorry, was just trying to add my vote as we just hit the problem, in case this PR needs some love ;)

**Comment by sigmavirus24** [comment]
Comments aren't for voting though. We have this planned we just don't have it entirely ready. This was also just to have a branch to have all the open PRs merged into one place so we can test all of them together. This isn't necessarily the PR that will actually merge to create 2.8.0

**Comment by L1ghtn1ng** [comment]
@sigmavirus24 IIRC Ubuntu either pulls from Debian testing or unstable during a new OS release cycle, so if #2567 was put in to one of those branches it will be in Ubuntu by now. Also you would be able to check the patches that are in the source for packaging as well. just my 2 cents

**Comment by Lukasa** [comment]
Ok, in preparation for releasing 2.8.0 I am going to merge this now. I'm aiming to get 2.8.0 out the door by the middle of this week, and merging this will help force me to do that.

**Pull request merged**
