### PR TITLE
Refactor prepare body

### PR DESCRIPTION
**Pull request by davidsoncasey**
PR for proposed/3.0 with refactoring of `prepare_body` method. For discussion see #3184.

### CODE REVIEW

**Comment by davidsoncasey** [comment]
I can take a look tonight and see if I can fix the conflict.

**Comment by davidsoncasey** [comment]
@Lukasa @nateprewitt I sort of forgot that this PR has been hanging out - is this still something we'd like to merge in? I can see about getting the conflicts fixed. Sorry I sort of lost momentum working on requests, I switched jobs and don't get time at work for open source projects any more.

**Comment by nateprewitt** [comment]
@davidsoncasey, no worries, thanks for taking the time to check back in! 😀

 @Lukasa may have more on this but I think moving [these tests](https://github.com/davidsoncasey/requests/blob/60e0349ce265378b127ae51e1853533b57eaac38/tests/test_requests.py#L1241-L1270) into a separate PR against master will be the most immediate benefit. This will show that the issue is currently fixed on master and allow us to close out #3066.

The work you did for `prepare_body` and `prepare_content_length` simplifies a lot of the logic and would be great for proposed/3.0.0. We'll need to merge master into the proposed/3.0.0 branch in this repo and then have you rebase your commits on top of it. I did some local testing and got this patch merged and working relatively pain free.

I'm also happy to help with any of the reshuffling of your commits if needed, just let us know.

**Comment by nateprewitt** [comment]
Hey @davidsoncasey, just checking back in. If you don't have any qualms with this, I'd like to open a PR rebasing 1a01007 and lines 1264-1270 in tests/test_requests.py (e5f0993) onto master next week. This will verify the work for #3066 is finished there and then we can revisit the `prepare_body` consolidation here whenever you're ready.

**Comment by nateprewitt** [comment]
@davidsoncasey, checking in again. It looks like @kennethreitz may want to start cleaning some of these older PRs up. There's still a lot of useful stuff in here that didn't make it into master but should be in 3.0.0. Would you be interested in bringing this branch up to date and fixing a few things? If not, I'll tidy up your commits and wrap this up.

**Comment by kennethreitz** [comment]
needs a rebase

**Comment by davidsoncasey** [comment]
@nateprewitt feel free to go ahead and tidy up and get this into master. I haven't had a chance to work on this project recently, and it would take me a little to get back up to speed on it.

**Comment by nateprewitt** [comment]
Thanks for checking back in @davidsoncasey, I'll move forward with rebasing this into a new PR then. All the best in whatever you're currently working on :)

**Comment by davidsoncasey** [comment]
Closing in favor of #3897

**Pull request closed without merging**
