### PR TITLE
Add exceptions into __init__.py

### PR DESCRIPTION
**Pull request by jtpereyda**
Addresses Issue #3022.

Also added the JetBrains IDE settings folder, `.idea/`, to `.gitignore`.

### CODE REVIEW

**Comment by Lukasa** [comment]
I'm going to leave this up to @kennethreitz. As you stated in #3022, this is totally unnecessary, but neither is it a maintenance burden, so I have no objection to it. Thanks for your contribution! :cake:

**Comment by kennethreitz** [comment]
We already have all the exceptions available in the public API:

``` python
from .exceptions import (
    RequestException, Timeout, URLRequired,
    TooManyRedirects, HTTPError, ConnectionError,
    FileModeWarning,
)
```

**Comment by sigmavirus24** [comment]
I'm with @kennethreitz this isn't necessary. Because of the line @kennethreitz is citing, users can already just do

``` py
import requests

try:
    r = requests.get(url)
except requests.ConnectionError:
    pass

# or

try:
   requests.get(url)
except requests.exceptions.ConnectionError:
   pass
```

Both work perfectly fine. Beyond that, we don't need a gitignore line for PyCharm/idea projects because that should already be in your [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by jtpereyda** [comment]
@kennethreitz Thanks, I was wondering about that line. Two questions:
1. That import makes them available as `requests.RequestException`. It's a subtle difference, but [this doc page](http://docs.python-requests.org/en/master/api/#exceptions) instructs users to include them as `requests.exceptions.RequestException`. Which one is the preferred or supported method?
   - If we want to include both, we could specify both in `__init__.py`.
   - If `requests.RequestException` is preferred (which I like), perhaps we should update the docs.
2. It looks like `ConnectTimeout` is missing from the list. Should it be added?

**Comment by jtpereyda** [comment]
@sigmavirus24 Thanks for the global gitignore tip! I hadn't heard about that.

**Comment by sigmavirus24** [comment]
@jtpereyda it's a subtle but unimportant difference. Try this in an interactive session:

``` py
>>> import requests
>>> try:
...     requests.get('http://localhost:8080')
... except requests.ConnectionError:
...     pass
...
>>> try:
...     requests.get('http://localhost:8080')
... except requests.exceptions.ConnectionError:
...     pass
...
>>>
```

Both already work perfectly fine. You can use either one or both interchangeably. If `ConnectTimeout` is missing, that should be added to the list of exceptions imported. But like I said, as it is now, we do not need to change anything for `requests.exceptions.RequestException` to work. It will simply work.

**Comment by kennethreitz** [comment]
@jtpereyda the "recommended" way is, in fact, `requests.RequestException`, as `requests.exceptions` is really just an internal namespacing.

That section of the docs are auto-generated from the codebase. I'd love to fix that section if we can. 

However, at this time, there's nothing broken about the docs or the code. We're just discussing room for possible usability improvement (which is the main goal of this library).

**Comment by kennethreitz** [comment]
@jtpereyda fixed the docs! http://docs.python-requests.org/en/master/api/#exceptions

**Comment by jtpereyda** [comment]
@kennethreitz Thanks!

**Pull request closed without merging**
