### PR TITLE
Use general null check for JSON

### LINKED ISSUE #2813: Requests json argument is ignored in 2.8.0
In version `2.7.0` I was using `Requests` constructor with `json` parameter specified, like:
```
json_data = [ ... ];
r = requests.Request('POST', url, json=json_data)
```

And in the `2.8.0` version this code does not work, because I do not specify `data` parameter. Inside constructor we get `self.data` assigned as `[] if data is None else data`, so we finally get `self.data` equal to `[]`.

And because of this commit: 7a0cd16c1a5be16f3df395ee12ed11d0ddde7837 we get `json` parameter ignored, because now we have to explicitly specify `data={}` when calling constructor, like:
```
json_data = [ ... ];
r = requests.Request('POST', url, json=json_data, data={})
```

I think that this issue definitely breaks documented API.

### PR DESCRIPTION
**Pull request by Lukasa**
Resolves #2813.

### CODE REVIEW

**Comment by Lukasa** [comment]
I think we're going to start needing some tests that our set of data-y parameters interact correctly together when using different parts of the API.

**Comment by sigmavirus24** [comment]
Or we need to stop duplicating logic everywhere that will break logic in different places.

**Comment by Lukasa** [comment]
Or both?

**Comment by sigmavirus24** [comment]
Yes. I commented in the wrong place. I greatly dislike the reliance on False-y values for tests. That should have been on #2813

**Pull request merged**
