### PR TITLE
[WIP] Set 'Transfer-Encoding: chunked' if data is a file with length 0

### LINKED ISSUE #2215: Using st_size on FIFO files or stdin will cause super_len to return 0 as the length
Hello,

### Use Case
I run a process using ```subprocess``` and give the stdout as data of a POST request. Since it is a file-descriptor, it has a fileno, and ```super_len()``` "stat" the file descriptor and use the st_size to determine the length.

The problem is: if the st_size returned is 0, it is possibly due to other reasons, in this case: the length is not determined (despite st_size is 0). But ```requests``` send a header specifying a ```Content-Length``` of 0 whilst it is actually not determined.

### Work Around
Wrap the stream in a generator, so the method ```fileno()``` cannot be accessed anymore.

```python
request.post(url, data=(x for x in p.stdout))
```

### Another Use Case
```
[14:05:31] ~ > mkfifo /tmp/a
[14:05:35] ~ > stat /tmp/a
  File: ‘/tmp/a’
  Size: 0               Blocks: 0          IO Block: 4096   fifo
Device: 1eh/30d Inode: 514910      Links: 1
Access: (0644/prw-r--r--)  Uid: ( 1001/ openerp)   Gid: (  100/   users)
Access: 2014-09-10 14:05:35.415835558 +0200
Modify: 2014-09-10 14:05:35.415835558 +0200
Change: 2014-09-10 14:05:35.415835558 +0200
 Birth: -
```
The size of a named pipe is 0.

### Fix
According to ```man 2 stat```:

> For most files under the /proc directory, stat() does not return the file size in the st_size field; instead the field is returned with the value 0.

I guess ```super_len()``` should return st_size if st_size if bigger than 0, otherwise ```None```.

### PR DESCRIPTION
**Pull request by BraulioVM**
Fixes #2215 

This is the first time I contribute to the project so I am not sure at all I put that code where it belongs. I know I have to add tests for this, but wanted to show you this beforehand.

Did I do this right?

Thank you

### CODE REVIEW

**Comment by Lukasa** [comment]
@BraulioVM This is a good first pass! I have a draft of this fix sitting around on my laptop, so when I get home I'll show you how I approached it and let you take the ideas you like best.

**Comment by BraulioVM** [comment]
@Lukasa Thanks!

I have just seen #2866, which won't allow me to implement the tests I want, so I might as well think of a solution for that issue.

**Comment by Lukasa** [comment]
So I think this change is not quite right. What we want is a simple change around line 437. Right now we test `length` for whether it is `None`: we should just broaden that to say `if length`. That way, we'll fall through to chunked encoding for zero-length files.

**Comment by BraulioVM** [comment]
I see. What I did didn't make any sense because file objects are _streams_. However, this change won't just affect files, it will affect any stream with length 0. Things will keep working, but I thought we just wanted to set 'Transfer-Encoding: chunked' if `data` was a file object with `super_len(data) == 0`.

**Comment by Lukasa** [comment]
@BraulioVM That's actually intentional: sending a chunked zero-length stream is fine, there won't be a problem there. That way, the code is clearer. =)

So, this change looks good to me, but I'll let @sigmavirus24 review it.

**Comment by BraulioVM** [comment]
Is there anything else I should do regarding this PR?

**Comment by Lukasa** [comment]
@BraulioVM Nope, just waiting for @sigmavirus24 to get enough time to swing by and take a look at it. =)

**Comment by sigmavirus24** [comment]
Woops! Sorry. I lost track of this with recent goings on IRL. This looks great to me! Thanks @BraulioVM

**Pull request merged**
