### PR TITLE
Import native Python JSON only

### PR DESCRIPTION
**Pull request by digitaldavenyc**
Pull Request derived from the discussion on issue #3052

### CODE REVIEW

**Comment by Lukasa** [comment]
LGTM.

**Comment by sigmavirus24** [comment]
:sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
Really, no longer a need for `json` to be in `compat` at all anymore, let alone be called `complexjson`. 

But, that would require touching a lot more code.

**Comment by digitaldavenyc** [comment]
@kennethreitz I actually was going to rename complexjson to json but there are json variable references all over the models.py file and decided it was probably best not to refactor it. If you still think it's a good idea I'm game to change it.

**Comment by digitaldavenyc** [comment]
Perhaps there a different name we could use for the import so it would require less touching of code. `jsonp`?

**Comment by kennethreitz** [comment]
Ah, prob best to `import json as complexjson` in `models.py` then (instead of `compat.py`).

It's a clever name, and I enjoy cleverness.

**Comment by digitaldavenyc** [comment]
Ha! Agreed, complexjson is a good alt name. Best to either change it to json or leave it as is.

**Comment by kennethreitz** [comment]
PR looks perfect.

**Comment by sigmavirus24** [comment]
The reason we need `complexjson` in `models.py` is because we accept `json` as a method/function parameter and for those cases we can't also reference `json` the module without a name collision. Leaving it as such makes life a bit simpler.

That said, I'm open to changing it to one of the following
- `loljson`
- `whyjson`
- `hailjson`
- `zomgjson`
- `whatevenisjson`

And probably quite a few other names. ;)

**Comment by kennethreitz** [comment]
- `mwson` (micro web services object notation)

**Comment by kennethreitz** [comment]
- `perhapsjson`
- `itcouldbejson`
- `pleasedontsayjason`

**Comment by kennethreitz** [comment]
No, it's fine as is.

**Comment by sigmavirus24** [comment]
I know. I'm just kidding about alternate names. Alternatively
- `mycathatesjson`
- `oneweirdtrickforserializinganddeserializingjson`

**Comment by kennethreitz** [comment]
- `magicjson`
- `sacredjson`
- `chopjsoncarrywater`
- `cosmicjson`

**Comment by digitaldavenyc** [comment]
I got it ...
- `trumpjson`

You guys are gonna delete the PR now aren't you :(

**Comment by kennethreitz** [comment]
TrumpJSON™: It's unbelievable, really, the best JSON you'll ever experience. Trust me, I know JSON.

**Comment by digitaldavenyc** [comment]
It overwrites all your code with this way better code, trust me it's better....

**Comment by sigmavirus24** [comment]
It's a huuuuuuuuuuuuuuuuuuge download. It makes serialization great again

**Comment by crccheck** [comment]
anyway this can get in a 2.x release? It's been two years now and `simplejson` is even less relevant than when this was authored

**Comment by nicmcd** [comment]
What is the status on this?

**Pull request merged**
