### PR TITLE
Added tests module

### PR DESCRIPTION
**Pull request by Stranger6667**
Hello, I want to propose some tests changes again :)

What is done:

1. All tests are moved to`tests` module.
2. All tests related to `requests.utils` are separated in `tests.test_utils` module.
3. Fixtures `httpbin` and `httpbin_secure` were slightly refactored and moved to `tests.conftest` module.
4. `ThreadPool` was removed, because it was not used.
5. All compatibility code was moved to `tests.compat`.
6. More parametrization was added.

I want to ask you if I'm going in the right way or not. Also I noticed, that `requests.utils` has ~45% coverage by unit tests, so, would you mind if I'll add more unit tests i this PR? If everything is ok

### CODE REVIEW

**Comment by Lukasa** [comment]
Pinging @kennethreitz again for review on test code.

Thanks for this @Stranger6667!

**Comment by kennethreitz** [comment]
This looks great! One minor nitpick about syntax, though.

You are using this style:

```python
@pytest.mark.parametrize(
    'timeout, error_text', (
        ((3, 4, 5), '(connect, read)'),
        ('foo', 'must be an int or float'),
    )
)
```

I would prefer this style:

```python
@pytest.mark.parametrize('timeout, error_text', 
    (
        ((3, 4, 5), '(connect, read)'),
        ('foo', 'must be an int or float'),
    )
)
```

But, I'd be happy to clean that up after the merge.

**Comment by kennethreitz** [comment]
@Stranger6667 more tests for `utils` are more than welcome!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by Stranger6667** [comment]
Thank you, @Lukasa @kennethreitz ! :)

**Pull request merged**
