### PR TITLE
remove weird characters from README.rst

### PR DESCRIPTION
**Pull request by jorgesumle**

### CODE REVIEW

**Comment by Lukasa** [comment]
There's no reason to remove these. What are you trying to achieve here?

**Comment by jorgesumle** [comment]
What are they? And what are they for? They are not displayed well in my computer.

From Readme in GitHub
captura de pantalla de 2016-11-29 10 05 31
From pip
captura de pantalla de 2016-11-29 10 05 43

**Comment by Lukasa** [comment]
They are [emoji](https://en.wikipedia.org/wiki/Emoji). They're pictograms that have been assigned Unicode glyphs. If your computer cannot render them you can either elect to resolve that by installing an emoji font, or you can simply ignore them: you aren't losing out on any critical data. The picture you can't see, for the record, is a slice of cake.

**Comment by kennethreitz** [comment]
The cake is a lie.

**Pull request closed without merging**
