### PR TITLE
Fix MisssingSchema error message does not handle unicode input correctly #2540

### PR DESCRIPTION
**Pull request by sh1buy**

### CODE REVIEW

**Comment by Lukasa** [comment]
I think this won't work on Python 3 with a binary URL, though I need to test that.

**Comment by sh1buy** [comment]
You rigth. This add 'b' to url. 

```
requests.exceptions.MissingSchema: Invalid URL b'example.com': 
No schema supplied. Perhaps you meant http://b'example.com'?
```

**Comment by sh1buy** [comment]
Whether it is necessary to display  URL completely in error message?
Will be enough only hostname?
For example, instead of the:

```
requests.exceptions.MissingSchema: Invalid URL 'example.com/page?query=blabla&foo=23': 
No schema supplied. Perhaps you meant 'http://example.com/page?query=blabla&foo=23'?
```

Output this:

```
requests.exceptions.MissingSchema: Invalid URL 'example.com/...': 
No schema supplied. Perhaps you meant 'http://example.com/...'?
```

Then we can solve this bug with applying IDNA to the hostname.

**Comment by Lukasa** [comment]
The better thing to do might be to call `to_native_str`, from our utility package.

**Comment by sh1buy** [comment]
This work in both Python's versions.

**Comment by Lukasa** [comment]
Can you wrap the line at 79 characters?

**Comment by sigmavirus24** [comment]
Thanks @sh1buy! :sparkles: :cake: :sparkles:

**Pull request merged**
