### PR TITLE
Update README to use Shields badges

### PR DESCRIPTION
**Pull request by iKevinY**
The SVG badges served by [Shields](http://shields.io) are friendlier to retina displays and have a standardized design.

Shields Comparison

### CODE REVIEW

**Comment by Lukasa** [comment]
No objection from me. @sigmavirus24?

**Comment by iKevinY** [comment]
One thing I noticed is that there's less precision in the download count – not sure if this problematic.

**Comment by sigmavirus24** [comment]
Meh. Download counts are working exactly correctly with PyPI at the moment anyway.

**Comment by sigmavirus24** [comment]
Thanks @iKevinY !

**Comment by iKevinY** [comment]
No worries!

**Pull request merged**
