### PR TITLE
Cut 2.7.0 this weekend

### PR DESCRIPTION
**Pull request by Lukasa**
Ok, I believe we've left enough time for the chunked stuff to bake, and no further issues seem to have come out of the woodwork. At this point, I think we should cut 2.7.0 and begin the switchover to our new release process.

@shazow are you open to tagging a new urllib3 release, and if so what commit would you like us to use? If you don't really care, by default we'd use shazow/urllib3@74073791a3429d9b9f375563954f57f2181599dc.

Things to do:

- [x] Update urllib3.
- [x] Confirm that the #2455 problem sites still work.
- [x] Update changelog.
- [ ] Tag.
- [ ] Push release.
- [ ] Have a drink.

### CODE REVIEW

**Comment by Lukasa** [comment]
In my ideal world we'd update the `certifi` bundle as well, but I'm now strongly averse to trying to do too much with these releases. @sigmavirus24?

**Comment by sigmavirus24** [comment]
I'm not strongly opposed to it. I'd like confirmation that the problem sites in #2455 at least work. Thoughts?

**Comment by Lukasa** [comment]
Agreed. Adding it to the list.

**Comment by Lukasa** [comment]
Alright, the chunked keep-alive problem does appear to be resolved after synchronizing urllib3.

**Comment by t-8ch** [comment]
Hm, this downgraded the embedded version string of urllib3.
I think it is confusing to have a quite arbitrary version in the bundled library.

Thoughts:
- Wait for a @shazow to cut a new release and update the version in urllib3 itself, then pull that.
- Rewrite the version string to be actual the commit id.

**Comment by shazow** [comment]
Tagged and pushed urllib3 v1.10.4.

**Comment by Lukasa** [comment]
And I updated the commit to resolve that problem. The only delta between the previous commit and the new one is the version identifier.

**Comment by Lukasa** [comment]
@sigmavirus24 Any objections to me merging this PR (manually without a merge commit, because we don't need it) and pushing the release?

**Comment by sigmavirus24** [comment]
0 (zero) objections here.

**Comment by Lukasa** [comment]
Done.

**Pull request merged**
