### PR TITLE
Deps (work in progress)

### PR DESCRIPTION
**Pull request by kennethreitz**
This pull request works on removing all vendored dependencies from Requests. 

Targeting v2.16.0. 

✨🍰✨

### CODE REVIEW

**Comment by kennethreitz** [comment]
all tests passing (on python 3 at least!)

**Comment by kennethreitz** [comment]
Remembering now why I hated Travis CI when it first launched.

**Comment by kennethreitz** [comment]
YOLO!

**Comment by jezdez** [comment]
👍

**Pull request merged**
