### PR TITLE
Fixed bug to give scheme proxy priority over "all"

### PR DESCRIPTION
**Pull request by shellhead**
Addresses bug called out in issue #3518.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This seems reasonable to me. @Lukasa thoughts?

**Comment by Lukasa** [comment]
This looks really good to me, I'm totally happy with it! Thanks so much @shellhead! :sparkles: :cake: :sparkles:

**Comment by drpoggi** [comment]
Shouldn't this line also be swapped to close out this issue? https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L229

**Comment by Lukasa** [comment]
Yup, looks like!

**Comment by sentientcucumber** [comment]
Thanks for pointing this out.

I'm also thinking I missed this as well https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L620

Is there any reason to not use `select_proxy` in sessions? It seems strange to have two different ways of selecting the proxy.

**Comment by Lukasa** [comment]
`select_proxy` does something subtly different. In this case in the session we are trying to recompute the proxies from the environment, but otherwise not to do anything.

**Pull request merged**
