### PR TITLE
Allow non-native-string method names.

### LINKED ISSUE #2818: TypeError after 2.7.0 -> 2.8.0 upgrade (cannot make memory view...)
I'm running into this traceback after upgrading to 2.8.0 from 2.7.0:
```
<snip>
    response = self.session.send(request)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 369, in send
    timeout=timeout
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
    data = memoryview(data)
TypeError: cannot make memory view because object does not have the buffer interface
```

The problem goes away after downgrading to 2.7.0.

A full traceback can be found [here](https://travis-ci.org/simon-weber/gmusicapi/jobs/82365307).

Here are the versions of relevant packages:
```
httplib2-0.9.2
ndg-httpsclient-0.4.0
pyasn1-0.1.9
pyasn1-modules-0.0.8
pyopenssl-0.15.1
requests-2.8.0
```

And a full list of packages:
```
MechanicalSoup-0.3.1
appdirs-1.4.0
beautifulsoup4-4.4.1
cffi-1.2.1
cryptography-1.0.2
decorator-4.0.4
enum34-1.0.4
gmusicapi-7.0.1.dev0
gpsoauth-0.0.4
httplib2-0.9.2
idna-2.0
ipaddress-1.0.14
mutagen-1.31
ndg-httpsclient-0.4.0
oauth2client-1.5.1
proboscis-1.2.6.0
protobuf-2.6.1
pyasn1-0.1.9
pyasn1-modules-0.0.8
pycparser-2.14
pycrypto-2.6.1
pyopenssl-0.15.1
python-dateutil-2.4.2
requests-2.8.0
rsa-3.2
six-1.10.0
validictory-1.0.1
```

Any ideas?

### PR DESCRIPTION
**Pull request by Lukasa**
Resolves #2818.

### CODE REVIEW

**Comment by Lukasa** [comment]
I'm starting with just the failing test to confirm that our environment can actually reproduce it.

**Comment by Lukasa** [comment]
@sigmavirus24 I'd like to slip this into 2.8.1, which I plan to release tomorrow. Mind doing a quick review before then?

**Comment by sigmavirus24** [comment]
I feel certain that we've fixed this already, perhaps in 3.0.0?

And a quick look shows we fixed it on July 18th: https://github.com/kennethreitz/requests/commit/ea1cbb3a1d9c6fb0edebb1bf0ac222c50054a367

I don't see discussion in the [bug](https://github.com/kennethreitz/requests/issues/2613) about why we didn't propose that against master though (although parts of it are backwards incompatible).

I'm +1 on fixing this and this looks like a good, simple, probably backwards compatible change.

**Comment by Lukasa** [comment]
Yeah, I don't really see why we didn't either. I think this fits here, and that past me was an idiot. =)

**Pull request merged**
