### PR TITLE
utils: let select_proxy not raise an exception when url has no hostname

### LINKED ISSUE #3131: utils.select_proxy raises an exception when URL has no hostname
URLs sometimes have no hostname (e.g. file URLs, or unix socket URLs). The parsed URL `hostname` attribute returns `None` in this case, making `utils.select_proxy` complain about concat'ing a `str` with `None`.

### PR DESCRIPTION
**Pull request by chipaca**
Fixes #3131.

### CODE REVIEW

**Comment by Lukasa** [comment]
While we're here, we should probably also handle the possibility that there's no scheme in the URL as well.

**Comment by chipaca** [comment]
scheme defaults to `''`, though. Well, more or less:

> The scheme argument gives the default addressing scheme, to be used only if the URL does not specify one. It should be the same type (text or bytes) as urlstring, except that the default value '' is always allowed, and is automatically converted to b'' if appropriate.

**Comment by Lukasa** [comment]
Urgh, `urlparse` is such an inconsistent function. Good spot.

**Comment by Lukasa** [comment]
Thanks! :sparkles: :cake: :sparkles:

**Pull request merged**
