### PR TITLE
Correct docstring for Response.ok

### PR DESCRIPTION
**Pull request by sigmavirus24**
We added a docstring just a few hours ago but it wasn't entirely accurate.

### CODE REVIEW

**Comment by Lukasa** [comment]
@sigmavirus24 That PR was merged on the grounds that it was consistent with the docstrings that relied on that method. If we're changing one, we should change them all. =)

**Comment by sigmavirus24** [comment]
@Lukasa which docstrings are those? I was under the impression that the docstring format was what was borrowed from, not the content of other docstrings.

**Comment by Lukasa** [comment]
`__bool__` and `__nonzero__`, immediately above.

**Comment by sigmavirus24** [comment]
I'll happily fix those too. In my opinion, misleading docs are worse than no docs. Those methods have been subject to criticism for years at this point and are targetted for correction in 3.0. May as well correct their documentation until 3.0 is out.

**Comment by sigmavirus24** [comment]
Updated `__bool__` and `__nonzero__`.

**Pull request merged**
