### PR TITLE
Expand on chunked handling.

### PR DESCRIPTION
**Pull request by Lukasa**
Once we merge in the new urllib3, this will update the docs to reflect the new best way to handle chunked transfer encoding.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
looks fine to me

how about specifying the size of a chunk? will it be possible?

**Comment by Lukasa** [comment]
Yup, passing the chunk size parameter to `iter_content` will do it. What you _can't_ do is change that size from chunk to chunk.

**Comment by TomasTomecek** [comment]
You are right! Should have checked the code.

The reason I asked because I was slightly confused by this sentence. I would probably update it to:

``` diff
-iterate chunk-by-chunk by calling ``iter_content`` with a chunk
-size parameter of ``None``.
+iterate chunk-by-chunk by calling ``iter_content`` (it is ``None``
+by default, but you can set chunk size yourself by providing an ``int``).
```

But you're the native speaker here. So I'm assuming that's just me not getting it.

**Comment by Lukasa** [comment]
Agree that it needs rewording, though that wording isn't quite right (it's not `None` by default, it's `1`).

**Comment by sigmavirus24** [comment]
pong

**Comment by Lukasa** [comment]
Always be updating PRs.

**Pull request merged**
