### PR TITLE
Recommended packages.

### PR DESCRIPTION
**Pull request by Lukasa**
Beginnings of work to have a list of recommended third-party (fourth-party?) packages.

@sigmavirus24 @kennethreitz feel free to push on top of this branch to add other things if you want.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@kennethreitz added the requests-toolbelt to the sidebar a while back. Would it be best to move it here?

**Comment by Lukasa** [comment]
Maybe have it here as well?

**Comment by kennethreitz** [comment]
Let's replace the toolbar link to a link to this page.

**Comment by sigmavirus24** [comment]
`==kennethreitz`. I'll push an update for that tonight I think

**Comment by kennethreitz** [comment]
@sigmavirus24 send another pr with that :)

**Pull request merged**
