### PR TITLE
Partially revert ab84f9be5740d4649d734e73b84f17f85e52ffc9

### PR DESCRIPTION
**Pull request by Lukasa**
As discussed in the comments for ab84f9be5740d4649d734e73b84f17f85e52ffc9, this code block is necessary thanks to our shiny `json` parameter.

As a temporary workaround, this reinstates the code Kenneth hates so much so that the builds start working again. @kennethreitz feel free to replace this with something else longer term if you still hate it. :grin:

### CODE REVIEW

**Comment by kennethreitz** [comment]
`import json as notsimplejson` :P

**Comment by Lukasa** [comment]
`import json as complexjson`? :grin:

**Comment by sigmavirus24** [comment]
`import json as _json` Really anything to make sure this works properly is a good thing.

**Comment by Lukasa** [comment]
ping @sigmavirus24

**Comment by sigmavirus24** [comment]
:+1: but the tests still seem to be broken because other things were relying on `json` being a module defined in `requests/models.py` http://ci.kennethreitz.org/job/requests-pr/662/PYTHON=2.7/console

**Comment by Lukasa** [comment]
I'm doubling down on complexjson here.

**Comment by sigmavirus24** [comment]
:cake:

**Comment by sigmavirus24** [comment]
Forgot something...

:sparkles: :cake: :sparkles:

**Pull request merged**
