### PR TITLE
made the quickstart more reader friendly

### LINKED ISSUE #2418: Data argument introduced too early in Quickstart guide
I'm following the quick start guide in:
http://docs.python-requests.org/en/latest/user/quickstart/
I got confused when reading the section "Custom Headers" because the example code features the data argument, which hasn't been introduced in the guide yet (it is the next section "More complicated POST requests" that describes the data argument).
My suggestion is to swap the order of those two sections, i.e. have "More complicated POST requests" before "Custom Headers", or modify the example code in "Custom Headers" (remove data argument).

### PR DESCRIPTION
**Pull request by yasoob**
Closes #2418

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Can we choose a better header to set? Or a better value? I can't see how a long user-agent string will be reader friendly. Some people will now start asking why all that information is necessary and what it means and why it's important. Why not use `headers={'Connection': 'close'}`?

**Comment by Lukasa** [comment]
Or just shorten the user-agent. `User-Agent: my-app/0.0.1` should do just fine.

**Comment by yasoob** [comment]
Made the string shorter.

**Comment by Lukasa** [comment]
Hurrah! :cake:

**Comment by yasoob** [comment]
Proud of my first contribution to requests :+1:  Here's a :cake: for everyone :smile:

**Comment by Lukasa** [comment]
@yasoob Feel free to open a pull request adding yourself to AUTHORS.rst!

**Pull request merged**
