### PR TITLE
Put the failing URL into the default RequestException string (issue 3430)

### PR DESCRIPTION
**Pull request by dhduvall**

### CODE REVIEW

**Comment by Lukasa** [comment]
I'm happy enough with this: :+1:

**Comment by sigmavirus24** [comment]
To be clear, I assigned @kennethreitz to this because I think this is something he's going to care about and have opinions about. I'm fine with this but I'll leave it to him to merge.

**Comment by kennethreitz** [comment]
#3430

**Comment by kennethreitz** [comment]
An example of what this would actually look like in practice would be nice. I'm not going to interrupt my workflow at the moment to download and see for myself. Maybe in a few days I will be.

**Comment by dhduvall** [comment]
At some point between 2.7.0 and 2.8.0, doing something like `requests.Session().request("GET", "http://badhostname/")` went from dropping

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/vendor-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/vendor-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/vendor-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(8, 'node name or service name not known'))
```

to

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='badhostname', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xed5ac0ec>: Failed to establish a new connection: [Errno 8] node name or service name not known',))
```

Same with connecting to a bad port on a good hostname, which was my original itch.  That's probably good enough for me, and just prepending the URL isn't super readable anymore, since it adds to an already very long line.  My apologies for making noise when an upgrade would have been sufficient (we've been on 2.6.0, but will be upgrading to 2.9 soon).

**Comment by Lukasa** [comment]
Thanks for following up @dhduvall, and thanks for the work, even though we will probably no longer accept it. =)

**Pull request closed without merging**
