### PR TITLE
Refactor default params

### PR DESCRIPTION
**Pull request by bsamek**
Specified the default argument for params that have a default in the docstring
so that the default is easier to see from the code. Modified the docstring in
api.py to match the docstring in sessions.py.

### CODE REVIEW

**Comment by bsamek** [comment]
I also noticed that there may be a problem in test_requests.py. Lines 524-5 reference the httpbin_ca_bundle fixture, but there is no fixture by that name. If I am reading this correctly, this means that the test is passing in None instead of a cert path. Does this make sense?

**Comment by sigmavirus24** [comment]
Hey @bsamek! Thanks for the PR.

I don't think we want to change the default parameters to the `request` method. We want to be able to discern between something that's a session setting and a request setting which we cannot do if we change that signature. We use [`merge_setting`](https://github.com/bsamek/requests/blob/master/requests/sessions.py#L49..L53) to make that determination and I don't think we want to break this.

Please revert that as the docstring changes _are_ desirable.

**Comment by bsamek** [comment]
Reverted the changes to the parameters. Kept the docstring changes.

Should I submit an issue regarding my earlier questions about the test?

**Comment by sigmavirus24** [comment]
There absolutely is such a fixture: https://github.com/kevin1024/pytest-httpbin/blob/master/pytest_httpbin/plugin.py#L40

**Comment by sigmavirus24** [comment]
Thanks again @bsamek !

**Comment by bsamek** [comment]
Ohhhhhhhhh I see. Thanks @sigmavirus24 !

**Comment by sigmavirus24** [comment]
Anytime @bsamek :) Thanks for the PR!

**Pull request merged**
