### PR TITLE
Fixes DeprecationWarnings in Python 3.6 due to invalid escape sequences

### LINKED ISSUE #3954: requests shows lots of DeprecationWarning on Python 3.6
Running tests on my project with the -Wd option now displays lots of DeprecationWarnings coming from requests.

From the Python 3.6 Changelog (https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior):
```A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases. (Contributed by Emanuel Barry in bpo-27364.)```

For reference, this is the commit that fixed those DeprecationWarnings in Django 1.11: https://github.com/django/django/commit/8119b679eb85cdc0ae3d321e54d06dd0200a1e82

### PR DESCRIPTION
**Pull request by rubendura**
Fixes #3954

### CODE REVIEW

**Comment by sigmavirus24** [comment]
> Using raw strings for docstrings tends to surprise people.

How so?

**Comment by sigmavirus24** [comment]
> My experience has been that people don't really grasp that you can prefix the string literal for docstrings, so they expect them to be plain strings.

My (admittedly anecdotal) experience has been with tools that suggest using raw-strings for this exact use-case (e.g., pydocstyle, etc.). *shrug* I don't particularly care either way.

**Comment by rubendura** [comment]
I personally prefer raw strings, they remove any ambiguity and make it clear that escape sequences do not work inside the string. They also remove noise which makes them easier to read. But I don't really care either.

Should I squash this commits or is it fine this way?

**Comment by Lukasa** [comment]
Squashing the commits might be nice.

**Comment by nateprewitt** [comment]
I'm not partial to either approach but as a data point [PEP257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring) seems to suggest raw docstrings are the way to go in the case of backslashes.

> Use r"""raw triple double quotes""" if you use any backslashes in your docstrings.

**Comment by Lukasa** [comment]
Hrm. I'll accept that as a preponderance of evidence that I'm an idiot then. ;) I'm outvoted 2-to-1, so back to raw strings we go. Sorry @rubendura!

**Comment by rubendura** [comment]
No worries. I'll revert that now.

**Comment by rubendura** [comment]
Done. Should be ready now :)

**Comment by Lukasa** [comment]
Yup, looks good. Thanks @rubendura!

**Pull request merged**
