### PR TITLE
Clarify Python versions supported by requests

### PR DESCRIPTION
**Pull request by drpoggi**
Remove some confusion in the Python versions supported by Requests.

### CODE REVIEW

**Comment by kennethreitz** [comment]
endashes (–) are appropriate for ranges, not hyphens. 

Let's also add "Requests officially supports".

**Comment by kennethreitz** [comment]
en dash, not em dash :)

It's cool, I'll fix it.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by drpoggi** [comment]
@kennethreitz thanks, tried copy pasting your en dash from above. Apparently GitHub's UI wasn't a fan of my methods.

**Pull request merged**
