### PR TITLE
Upgrade urllib3 to 490d3a227fadb626cd54a240b9d0922f849914b4

### PR DESCRIPTION
**Pull request by Yasumoto**
This is the release tagged at 85dfc16817df1e3604c238ad5d64f3b229e0598b

### CODE REVIEW

**Comment by Yasumoto** [comment]
Tested on OS X 10.10:

```
[tw-mbp-jsmith requests (urllib_upgrade)]$ make test
# This runs all of the tests. To run an individual test, run py.test with
# the -k flag, like "py.test -k test_path_is_not_double_encoded"
py.test test_requests.py
============================================================================== test session starts ===============================================================================
platform darwin -- Python 2.7.9 -- pytest-2.3.4
plugins: cov
collected 154 items 

test_requests.py ..........................................................................................................................................................

========================================================================== 154 passed in 26.34 seconds ===========================================================================
```

This is to get https://github.com/shazow/urllib3/pull/526 merged in https://github.com/pypa/pip/issues/2395 can take advantage of the fix for older SSL library versions. This was previously tracked at https://github.com/kennethreitz/requests/issues/2435.

**Comment by sigmavirus24** [comment]
We actually will pull in tip when we do a release. Speaking of which @Lukasa when do you think we should do a release? There's extra header awesomeness that's unreleased in urllib3 (merged last night) that I'd like to grab before doing a release.

**Comment by Yasumoto** [comment]
@sigmavirus24 sounds good- I updated to HEAD, but feel free to drop this PR in favor of another one if this is in flight elsewhere.

**Comment by bcail** [comment]
It'd be great to get a bug-fix release soon (for issue #2435), so that we can use requests on python 2.7.9...

**Comment by Yasumoto** [comment]
Howdy all, anything I can do to help get this over the finish line? Happy to pitch in on testing or updating docs for 'upgrading urllib3' if I missed something too.

Thanks!!

**Comment by patsoffice** [comment]
This is a pretty big blocker for me right now. Any chance we can get this pull request merged soon?

**Comment by Yasumoto** [comment]
Thanks @sigmavirus24 !

**Pull request merged**
