### PR TITLE
Document Response.iter_lines() deficiencies

### PR DESCRIPTION
**Pull request by plaes**

### CODE REVIEW

**Comment by Lukasa** [comment]
@plaes This is a great PR. One small note however, we don't use `unittest`, we use `pytest`. This is why your test suite failed: `unittest.expectedFailure` doesn't exist in Python 2.6. Instead, use [`pytest.mark.xfail`](http://pytest.org/latest/skipping.html#mark-a-test-function-as-expected-to-fail).

**Comment by plaes** [comment]
Oops.. I push forced the fix.

**Comment by Lukasa** [comment]
Hurrah! Thanks so much for this @plaes!

**Comment by Lukasa** [comment]
:cake: :star:

**Comment by sigmavirus24** [comment]
Thanks @plaes!

**Pull request merged**
