### PR TITLE
fix contextlib.closing bug for sessions where content is not consumed…

### PR DESCRIPTION
**Pull request by colindickson**
… (issue #2593)

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Why are you making 25 requests to three websites that we don't use anywhere else in the test suite?

**Comment by colindickson** [comment]
mainly as an attempt to reproduce the bug demonstrated in the original issue.   i suppose i could simplify it a great deal

**Comment by sigmavirus24** [comment]
Please don't create a new pull request. If you continue to push commits to this branch they'll just show up here.

**Comment by sigmavirus24** [comment]
Also, let me be clear, your fix here is 100% correct.

**Comment by colindickson** [comment]
test should be better now :)

**Comment by Lukasa** [comment]
LGTM. :cake:

**Pull request merged**
