### PR TITLE
Move native string conversion to Request

### LINKED ISSUE #2613: Prepared requests containing binary files will not send when unicode_literals is imported
```python
#!/usr/bin/env python                                                                                                                                                              
from __future__ import unicode_literals
import requests
import sys


def main():
    request = requests.Request(method='PUT', url='https://httpbin.org/put')
    with open(sys.argv[1], 'rb') as fp:
        request.files = {'hello': fp}
        prepared = request.prepare()
        requests.Session().send(prepared)

if __name__ == '__main__':
    sys.exit(main())
```

The above program works perfectly in python3, and in python2 when `unicode_literals` is not imported. If the request isn't prepared it works without a problem unfortunately, I require both prepared requests and `unicode_literals` in my project.

The exception raised is:

```
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    sys.exit(main())
  File "./test.py", line 12, in main
    requests.Session().send(prepared)
  File "/Users/bboe/.venv/p27/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bboe/.venv/p27/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/bboe/.venv/p27/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/bboe/.venv/p27/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 109: ordinal not in range(128)```

### PR DESCRIPTION
**Pull request by Lukasa**
This fixes #2613. I believe that this technically constitutes a backward-incompatible API change, so I've proposed this against 3.0.0. Let me know if you disagree @sigmavirus24 (the other option is really that this is a bugfix), and I'll propose against master.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
hehehe The tests are trying to pass `None` as a method. We should either change that default or fix the tests.

**Comment by Lukasa** [comment]
Grr.

**Comment by sigmavirus24** [comment]
Stupid question: Why default to an empty string if method is None? I'm not entirely comfortable with that

**Comment by Lukasa** [comment]
Yeah, it was definitely a bit of a blind shot. A better idea might just be to have no default for `method`. I can't think of anything else non-surprising.

**Comment by sigmavirus24** [comment]
@Lukasa thoughts on the last commit that I pushed?

**Comment by sigmavirus24** [comment]
Note that if we want to present a better error to the user, we can catch the error raised by `to_native_string` and raise a new one.

**Comment by Lukasa** [comment]
If we're going this route, we should remove the default argument from `method`, as it cannot safely be used any longer.

**Comment by sigmavirus24** [comment]
I feel like using an empty string as a default value is a footgun. That said, I don't feel strongly about whether method should be a required argument. Currently, in our own code we do, one might do

``` py
req = requests.Request()
self.update_request(req)
prepped = req.prepare()
```

I think this is something valid for someone to do. That said, perhaps `req.prepare` could raise a `ValueError`, `TypeError`, or something more descriptive that we include in `requests.exceptions`? That stops the user from shooting themselves in the foot and then we just move the `to_native_string` into `Request.prepare` or into `PreparedRequest.prepare_method`. In fact, I think that `PreparedRequest.prepare_method` should actually be where we raise the exception. Currently, we do nothing if `method` is `None` and I'm pretty sure that's bad.

**Comment by Lukasa** [comment]
I can see the advantage in that approach, I'd be ok with that.

**Comment by sigmavirus24** [comment]
@Lukasa updated with that approach.

**Comment by sigmavirus24** [comment]
ping

**Pull request merged**
