### PR TITLE
pysocks 1.5.7 blacklisting, due to IPv6 problems

### PR DESCRIPTION
**Pull request by Trodis**
https://github.com/kennethreitz/requests/issues/3551

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Thanks @Trodis!

**Comment by sigmavirus24** [comment]
✨ 🍰 ✨

**Comment by nano3k0a** [comment]
Glad I could help and thanks @Lukasa

**Comment by Lukasa** [comment]
My pleasure: sorry that you bumped into this!

**Pull request merged**
