### PR TITLE
make setup.py upload happy

### PR DESCRIPTION
**Pull request by heni**
distutils brokes when we use tuple based meta values
canonic way is define classifiers as list not a tuple

### CODE REVIEW

**Comment by Lukasa** [comment]
@heni We've been using a tuple here since [literally the start of the project](https://github.com/kennethreitz/requests/commit/0477018761c67152cdcc0b83d56f27e701e65b9e), which _used_ distutils. I do not believe this can possibly be the problem you're experiencing.

**Comment by heni** [comment]
I want to redistribute this package into private repository of our project and with tuple for classifiers I have broken next chain of commands
  pip3 install --download=. --no-binary=:all: requests
  tar xf requests-2.9.0.tar.gz
  cd requests-2.9.0
  python3 setup.py bdist_wheel upload -r private-repo

**Comment by Lukasa** [comment]
Distutils does not work with wheel, you have to use setuptools.

**Comment by sigmavirus24** [comment]
Also `setup.py upload` most likely is _not_ performing certificate validation. Use `twine` instead.

**Pull request closed without merging**
